# Generated by Django 3.2.15 on 2023-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_auto_20221229_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='Otros_elementos_patrimonial',
            field=models.TextField(blank=True, default=''),
        ),
    ]
