# Generated by Django 3.2.15 on 2023-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_auto_20230228_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='plan_cerro_poblacion',
            field=models.CharField(blank=True, choices=[('PLAN', 'Plan'), ('CERRO', 'Cerro'), ('POBLACION', 'Poblacion')], default='PLAN', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_pisos_superiores',
            field=models.CharField(blank=True, choices=[('', ''), ('VIVIENDA', 'Vivienda'), ('COMERCIO', 'Comercio'), ('SERVICIO', 'Servicio'), ('EDUCACION', 'Educacion'), ('SALUD', 'Salud'), ('DEPORTE', 'Deporte'), ('RECREACION', 'Recreacion'), ('CULTURA', 'Cultura'), ('CULTO', 'Culto'), ('INDUSTRIA', 'Industria'), ('BODEGA', 'Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_primer_piso',
            field=models.CharField(blank=True, choices=[('', ''), ('VIVIENDA', 'Vivienda'), ('COMERCIO', 'Comercio'), ('SERVICIO', 'Servicio'), ('EDUCACION', 'Educacion'), ('SALUD', 'Salud'), ('DEPORTE', 'Deporte'), ('RECREACION', 'Recreacion'), ('CULTURA', 'Cultura'), ('CULTO', 'Culto'), ('INDUSTRIA', 'Industria'), ('BODEGA', 'Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_subterraneo',
            field=models.CharField(blank=True, choices=[('', ''), ('VIVIENDA', 'Vivienda'), ('COMERCIO', 'Comercio'), ('SERVICIO', 'Servicio'), ('EDUCACION', 'Educacion'), ('SALUD', 'Salud'), ('DEPORTE', 'Deporte'), ('RECREACION', 'Recreacion'), ('CULTURA', 'Cultura'), ('CULTO', 'Culto'), ('INDUSTRIA', 'Industria'), ('BODEGA', 'Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_pisos_superiores',
            field=models.CharField(blank=True, choices=[('', ''), ('VIVIENDA', 'Vivienda'), ('COMERCIO', 'Comercio'), ('SERVICIO', 'Servicio'), ('EDUCACION', 'Educacion'), ('SALUD', 'Salud'), ('DEPORTE', 'Deporte'), ('RECREACION', 'Recreacion'), ('CULTURA', 'Cultura'), ('CULTO', 'Culto'), ('INDUSTRIA', 'Industria'), ('BODEGA', 'Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_primer_piso',
            field=models.CharField(blank=True, choices=[('', ''), ('VIVIENDA', 'Vivienda'), ('COMERCIO', 'Comercio'), ('SERVICIO', 'Servicio'), ('EDUCACION', 'Educacion'), ('SALUD', 'Salud'), ('DEPORTE', 'Deporte'), ('RECREACION', 'Recreacion'), ('CULTURA', 'Cultura'), ('CULTO', 'Culto'), ('INDUSTRIA', 'Industria'), ('BODEGA', 'Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_subterraneo',
            field=models.CharField(blank=True, choices=[('', ''), ('VIVIENDA', 'Vivienda'), ('COMERCIO', 'Comercio'), ('SERVICIO', 'Servicio'), ('EDUCACION', 'Educacion'), ('SALUD', 'Salud'), ('DEPORTE', 'Deporte'), ('RECREACION', 'Recreacion'), ('CULTURA', 'Cultura'), ('CULTO', 'Culto'), ('INDUSTRIA', 'Industria'), ('BODEGA', 'Bodega')], default='VIVIENDA', max_length=255),
        ),
    ]
