# Generated by Django 3.2.15 on 2023-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_auto_20230228_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicasmorfologicas',
            name='descripcion_del_inmubebles',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
