# Generated by Django 3.2.15 on 2023-03-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_auto_20230301_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasmorfologicas',
            name='materialidad_cubierta',
            field=models.CharField(blank=True, choices=[('FIBROCEMENTO', 'Fibrocemento'), ('TEJAS', 'Tejas'), ('TEJUELA (ZINC)', 'Tejuela (Zinc)'), ('ACERO GALVANIZADO', 'Acero Galvanizado')], default='ACERO', max_length=50),
        ),
        migrations.AlterField(
            model_name='caracteristicasmorfologicas',
            name='materialidad_revestimientos',
            field=models.CharField(blank=True, choices=[('ENLUCIDO/ESTUCO', 'Enlucido/estuco'), ('MADERA', 'Madera'), ('PLACHA TOLENADA', 'Placha tolenada'), ('HORMIGON ', 'Hormigo a la vista')], default='ENLUCIDO/ESTUCO', max_length=255),
        ),
        migrations.AlterField(
            model_name='relaciondelinmuebleconelterreno',
            name='Otros_elementos_patrimonial',
            field=models.TextField(blank=True, choices=[('PLACA EN FACHADA', 'Placa en fachada'), ('ESCULTURA', 'Escultura'), ('MONUMENTOS PUBLICOS', 'Monumentos publicos'), ('RELACION VISUAL', 'Relacion visual')], default='PLACA EN FACHADA'),
        ),
    ]
