# Generated by Django 3.2.15 on 2023-03-06 16:43

from django.db import migrations, models
import ficha.models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_auto_20230302_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoubicacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ficha.models.content_file_name_plano),
        ),
    ]
