# Generated by Django 3.2.15 on 2023-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_alter_planoubicacion_imagen_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasmorfologicas',
            name='materialidad_revestimientos',
            field=models.CharField(blank=True, choices=[('ENLUCIDO/ESTUCO', 'Enlucido/estuco'), ('MADERA', 'Madera'), ('PLACHA TOLENADA', 'Placha tolenada'), ('HORMIGON ', 'Hormigo a la vista'), ('OTRO', 'Otro')], default='ENLUCIDO/ESTUCO', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_pisos_superiores',
            field=models.CharField(blank=True, choices=[('', ''), ('1 - VIVIENDA', '1 - Vivienda'), ('2 - COMERCIO', '2 - Comercio'), ('3 - SERVICIO', '3 - Servicio'), ('4 - EDUCACION', '4 - Educacion'), ('5 - SALUD', '5 - Salud'), ('6 - DEPORTE', '6 - Deporte'), ('7 - RECREACION', '7 - Recreacion'), ('8 - CULTURA', '8 - Cultura'), ('9 - CULTO', '9 - Culto'), ('10 - INDUSTRIA', '10 - Industria'), ('11 - BODEGA', '11 - Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_primer_piso',
            field=models.CharField(blank=True, choices=[('', ''), ('1 - VIVIENDA', '1 - Vivienda'), ('2 - COMERCIO', '2 - Comercio'), ('3 - SERVICIO', '3 - Servicio'), ('4 - EDUCACION', '4 - Educacion'), ('5 - SALUD', '5 - Salud'), ('6 - DEPORTE', '6 - Deporte'), ('7 - RECREACION', '7 - Recreacion'), ('8 - CULTURA', '8 - Cultura'), ('9 - CULTO', '9 - Culto'), ('10 - INDUSTRIA', '10 - Industria'), ('11 - BODEGA', '11 - Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_subterraneo',
            field=models.CharField(blank=True, choices=[('', ''), ('1 - VIVIENDA', '1 - Vivienda'), ('2 - COMERCIO', '2 - Comercio'), ('3 - SERVICIO', '3 - Servicio'), ('4 - EDUCACION', '4 - Educacion'), ('5 - SALUD', '5 - Salud'), ('6 - DEPORTE', '6 - Deporte'), ('7 - RECREACION', '7 - Recreacion'), ('8 - CULTURA', '8 - Cultura'), ('9 - CULTO', '9 - Culto'), ('10 - INDUSTRIA', '10 - Industria'), ('11 - BODEGA', '11 - Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_pisos_superiores',
            field=models.CharField(blank=True, choices=[('', ''), ('1 - VIVIENDA', '1 - Vivienda'), ('2 - COMERCIO', '2 - Comercio'), ('3 - SERVICIO', '3 - Servicio'), ('4 - EDUCACION', '4 - Educacion'), ('5 - SALUD', '5 - Salud'), ('6 - DEPORTE', '6 - Deporte'), ('7 - RECREACION', '7 - Recreacion'), ('8 - CULTURA', '8 - Cultura'), ('9 - CULTO', '9 - Culto'), ('10 - INDUSTRIA', '10 - Industria'), ('11 - BODEGA', '11 - Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_primer_piso',
            field=models.CharField(blank=True, choices=[('', ''), ('1 - VIVIENDA', '1 - Vivienda'), ('2 - COMERCIO', '2 - Comercio'), ('3 - SERVICIO', '3 - Servicio'), ('4 - EDUCACION', '4 - Educacion'), ('5 - SALUD', '5 - Salud'), ('6 - DEPORTE', '6 - Deporte'), ('7 - RECREACION', '7 - Recreacion'), ('8 - CULTURA', '8 - Cultura'), ('9 - CULTO', '9 - Culto'), ('10 - INDUSTRIA', '10 - Industria'), ('11 - BODEGA', '11 - Bodega')], default='VIVIENDA', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_subterraneo',
            field=models.CharField(blank=True, choices=[('', ''), ('1 - VIVIENDA', '1 - Vivienda'), ('2 - COMERCIO', '2 - Comercio'), ('3 - SERVICIO', '3 - Servicio'), ('4 - EDUCACION', '4 - Educacion'), ('5 - SALUD', '5 - Salud'), ('6 - DEPORTE', '6 - Deporte'), ('7 - RECREACION', '7 - Recreacion'), ('8 - CULTURA', '8 - Cultura'), ('9 - CULTO', '9 - Culto'), ('10 - INDUSTRIA', '10 - Industria'), ('11 - BODEGA', '11 - Bodega')], default='VIVIENDA', max_length=255),
        ),
    ]
