# Generated by Django 3.2.15 on 2023-03-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_auto_20230308_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='fecha_registro_fotografico',
            field=models.DateField(default='2023-03-14'),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='rol',
            field=models.CharField(blank=True, default='00000-00000', max_length=100),
        ),
    ]
