# Generated by Django 3.2.15 on 2023-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0014_auto_20230316_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='fecha_registro_fotografico',
            field=models.DateField(auto_now=True),
        ),
    ]
