# Generated by Django 3.2.15 on 2023-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0015_alter_fotografiacontexto_fecha_registro_fotografico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='id_plano',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
