# Generated by Django 3.2.15 on 2023-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0016_alter_identificacioninmueble_id_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenapatrimonial',
            old_name='valor_economico_social',
            new_name='valor_economico',
        ),
        migrations.AddField(
            model_name='resenapatrimonial',
            name='valor_social',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='valoracionatributos',
            name='valor_resumen',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
