# Generated by Django 3.2.15 on 2023-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0017_auto_20230804_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracionatributos',
            old_name='valor_economico_social_a',
            new_name='valor_economico_a',
        ),
        migrations.RenameField(
            model_name='valoracionatributos',
            old_name='valor_economico_social_b',
            new_name='valor_economico_b',
        ),
        migrations.RenameField(
            model_name='valoracionatributos',
            old_name='valor_economico_social_c',
            new_name='valor_economico_c',
        ),
        migrations.AddField(
            model_name='valoracionatributos',
            name='valor_social_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='valoracionatributos',
            name='valor_social_b',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='valoracionatributos',
            name='valor_social_c',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
