# Generated by Django 3.2.15 on 2023-08-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0018_auto_20230804_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracionatributos',
            old_name='valor_economico_c',
            new_name='valor_historico_c',
        ),
        migrations.RemoveField(
            model_name='valoracionatributos',
            name='valor_social_b',
        ),
        migrations.RemoveField(
            model_name='valoracionatributos',
            name='valor_social_c',
        ),
    ]
