# Generated by Django 3.2.15 on 2023-08-16 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ficha.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0020_identificacioninmueble_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicasmorfologicas',
            name='fotografia_contexto_1',
            field=models.ImageField(blank=True, null=True, upload_to=ficha.models.content_file_name_contexto_1),
        ),
        migrations.AddField(
            model_name='caracteristicasmorfologicas',
            name='fotografia_contexto_2',
            field=models.ImageField(blank=True, null=True, upload_to=ficha.models.content_file_name_contexto_2),
        ),
        migrations.AddField(
            model_name='caracteristicasmorfologicas',
            name='fotografia_contexto_3',
            field=models.ImageField(blank=True, null=True, upload_to=ficha.models.content_file_name_contexto_3),
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_1',
            field=models.ImageField(blank=True, default='', upload_to=ficha.models.content_file_name_contexto_1),
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_2',
            field=models.ImageField(blank=True, default='', upload_to=ficha.models.content_file_name_contexto_2),
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_plano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verificacion',
                'verbose_name_plural': 'verificaciones',
            },
        ),
    ]
