# Generated by Django 3.2.15 on 2023-08-16 15:41

from django.db import migrations, models
import ficha.models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0021_auto_20230816_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacion',
            old_name='usuario',
            new_name='usuario_trabajador',
        ),
        migrations.AddField(
            model_name='verificacion',
            name='usuario_revisor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_1',
            field=models.ImageField(blank=True, default='', upload_to=ficha.models.content_file_name_contexto_1),
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_2',
            field=models.ImageField(blank=True, default='', upload_to=ficha.models.content_file_name_contexto_2),
        ),
    ]
