# Generated by Django 3.2.15 on 2023-08-17 14:52

from django.conf import settings
from django.db import migrations, models
import ficha.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0024_auto_20230816_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verificacion',
            new_name='observacion',
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_1',
            field=models.ImageField(blank=True, default='', upload_to=ficha.models.content_file_name_contexto_1),
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_2',
            field=models.ImageField(blank=True, default='', upload_to=ficha.models.content_file_name_contexto_2),
        ),
    ]
